// ============================================================================
// clearance_dds_subscriber.exe - standalone cross-process DDS subscriber.
//
// Runs OUTSIDE Unreal. Subscribes to all six clearance/* topics on the same
// domain the CLEARANCE publisher is running on (default 0), prints received
// samples to stdout. Because this process has a different PID and different
// address space, Fast DDS cannot use the intra-process transport shortcut
// that suppresses wire traffic when publisher + subscriber are co-located -
// which means Wireshark's RTPS filter will show a continuous stream of user-
// data packets flowing from the CLEARANCE publisher into this process. The
// visible wire evidence for the demo video.
//
// Build: run build_subscriber.bat in this folder (needs vcvars64 + eProsima
// Fast DDS SDK at C:/Program Files/eProsima/fastdds 3.6.1.0/ or the
// FASTDDS_HOME env var pointing elsewhere).
//
// Run: clearance_dds_subscriber.exe [domain]
//   default domain 0. Match whatever `clearance.dds.start <N>` was passed
//   inside the sim. - TripleA
// ============================================================================

// Generated types come from the ClearanceDDS module - included via -I
// switch pointed at ../Source/ClearanceDDS/Private/Generated by the .bat.
#include "AirspaceTelemetry.hpp"
#include "AirspaceTelemetryPubSubTypes.hpp"

#include <fastdds/dds/domain/DomainParticipant.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/domain/qos/DomainParticipantQos.hpp>
#include <fastdds/dds/subscriber/DataReader.hpp>
#include <fastdds/dds/subscriber/DataReaderListener.hpp>
#include <fastdds/dds/subscriber/SampleInfo.hpp>
#include <fastdds/dds/subscriber/Subscriber.hpp>
#include <fastdds/dds/subscriber/qos/DataReaderQos.hpp>
#include <fastdds/dds/subscriber/qos/SubscriberQos.hpp>
#include <fastdds/dds/topic/Topic.hpp>
#include <fastdds/dds/topic/TypeSupport.hpp>

#include <atomic>
#include <chrono>
#include <csignal>
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <iomanip>
#include <iostream>
#include <string>
#include <thread>

using namespace eprosima::fastdds::dds;

namespace
{
	std::atomic<bool> gShouldExit{ false };
	std::atomic<std::uint64_t> gReceivedCount{ 0 };

	void on_signal(int) { gShouldExit.store(true); }

	template <typename SampleT>
	class TListener : public DataReaderListener
	{
	public:
		const char* Label = "unknown";

		void on_data_available(DataReader* Reader) override
		{
			SampleT Sample;
			SampleInfo Info;
			while (Reader->take_next_sample(&Sample, &Info) == RETCODE_OK)
			{
				if (!Info.valid_data) { continue; }
				gReceivedCount.fetch_add(1, std::memory_order_relaxed);
				PrintSample(Sample);
			}
		}

	private:
		void PrintSample(const SampleT& S) const;
	};

	// Specialisations per topic - keeps the print format explicit per type. - TripleA
	template <>
	void TListener<ClearanceDDS::AircraftState>::PrintSample(const ClearanceDDS::AircraftState& S) const
	{
		std::cout << "[AircraftState] entity=" << S.EntityNumber()
		          << " marking=" << S.Marking()
		          << " pos=(" << std::fixed << std::setprecision(1)
		          << S.XMeters() << "," << S.YMeters() << "," << S.ZMeters() << ")"
		          << " v=(" << S.VxMps() << "," << S.VyMps() << "," << S.VzMps() << ")\n";
	}

	template <>
	void TListener<ClearanceDDS::FireEvent>::PrintSample(const ClearanceDDS::FireEvent& S) const
	{
		std::cout << "[FireEvent] firer=" << S.FiringEntity()
		          << " target=" << S.TargetEntity()
		          << " munition=" << S.MunitionEntity()
		          << " event=" << S.EventNumber() << "\n";
	}

	template <>
	void TListener<ClearanceDDS::DetonationEvent>::PrintSample(const ClearanceDDS::DetonationEvent& S) const
	{
		std::cout << "[DetonationEvent] firer=" << S.FiringEntity()
		          << " target=" << S.TargetEntity()
		          << " result=" << static_cast<int>(S.DetonationResult())
		          << " event=" << S.EventNumber() << "\n";
	}

	template <>
	void TListener<ClearanceDDS::EmissionSnapshot>::PrintSample(const ClearanceDDS::EmissionSnapshot& S) const
	{
		std::cout << "[EmissionSnapshot] entity=" << S.EmittingEntity()
		          << " emitter=" << S.EmitterName()
		          << " painted=" << S.PaintedEntityNumbers().size() << "\n";
	}

	template <>
	void TListener<ClearanceDDS::TransmitterState>::PrintSample(const ClearanceDDS::TransmitterState& S) const
	{
		std::cout << "[TransmitterState] entity=" << S.OwnerEntity()
		          << " freq=" << S.FrequencyHz() << "Hz"
		          << " state=" << static_cast<int>(S.TransmitState()) << "\n";
	}

	template <>
	void TListener<ClearanceDDS::SignalEvent>::PrintSample(const ClearanceDDS::SignalEvent& S) const
	{
		std::string Text(reinterpret_cast<const char*>(S.Data().data()), S.Data().size());
		std::cout << "[SignalEvent] entity=" << S.OwnerEntity()
		          << " radio=" << S.RadioId()
		          << " text=\"" << Text << "\"\n";
	}
}

int main(int argc, char** argv)
{
	std::uint32_t Domain = 0;
	if (argc >= 2) { Domain = static_cast<std::uint32_t>(std::atoi(argv[1])); }

	std::cout << "clearance_dds_subscriber - listening on domain " << Domain << "\n";
	std::cout << "Ctrl-C to exit\n\n";

	std::signal(SIGINT, on_signal);

	DomainParticipantFactory* Factory = DomainParticipantFactory::get_instance();
	if (!Factory) { std::cerr << "no DomainParticipantFactory\n"; return 1; }

	DomainParticipant* Participant = Factory->create_participant(Domain, PARTICIPANT_QOS_DEFAULT);
	if (!Participant) { std::cerr << "create_participant failed\n"; return 2; }

	// Register the six generated types.
	TypeSupport AircraftStateType   { new ClearanceDDS::AircraftStatePubSubType() };
	TypeSupport FireEventType       { new ClearanceDDS::FireEventPubSubType() };
	TypeSupport DetonationEventType { new ClearanceDDS::DetonationEventPubSubType() };
	TypeSupport EmissionType        { new ClearanceDDS::EmissionSnapshotPubSubType() };
	TypeSupport TransmitterType     { new ClearanceDDS::TransmitterStatePubSubType() };
	TypeSupport SignalType          { new ClearanceDDS::SignalEventPubSubType() };
	AircraftStateType  .register_type(Participant);
	FireEventType      .register_type(Participant);
	DetonationEventType.register_type(Participant);
	EmissionType       .register_type(Participant);
	TransmitterType    .register_type(Participant);
	SignalType         .register_type(Participant);

	Subscriber* Sub = Participant->create_subscriber(SUBSCRIBER_QOS_DEFAULT);

	auto MakeTopic = [&](const char* Name, TypeSupport& Type) -> Topic*
	{
		return Participant->create_topic(Name, Type.get_type_name(), TOPIC_QOS_DEFAULT);
	};

	Topic* T_Aircraft    = MakeTopic("clearance/aircraft/state",    AircraftStateType);
	Topic* T_Fire        = MakeTopic("clearance/weapons/fire",      FireEventType);
	Topic* T_Detonation  = MakeTopic("clearance/weapons/detonation",DetonationEventType);
	Topic* T_Emission    = MakeTopic("clearance/radar/emission",    EmissionType);
	Topic* T_Transmitter = MakeTopic("clearance/radio/transmitter", TransmitterType);
	Topic* T_Signal      = MakeTopic("clearance/radio/signal",      SignalType);

	TListener<ClearanceDDS::AircraftState>    L_Aircraft;    L_Aircraft.Label    = "aircraft/state";
	TListener<ClearanceDDS::FireEvent>        L_Fire;        L_Fire.Label        = "weapons/fire";
	TListener<ClearanceDDS::DetonationEvent>  L_Detonation;  L_Detonation.Label  = "weapons/detonation";
	TListener<ClearanceDDS::EmissionSnapshot> L_Emission;    L_Emission.Label    = "radar/emission";
	TListener<ClearanceDDS::TransmitterState> L_Transmitter; L_Transmitter.Label = "radio/transmitter";
	TListener<ClearanceDDS::SignalEvent>      L_Signal;      L_Signal.Label      = "radio/signal";

	DataReaderQos ReaderQos = DATAREADER_QOS_DEFAULT;
	ReaderQos.reliability().kind = BEST_EFFORT_RELIABILITY_QOS;

	Sub->create_datareader(T_Aircraft,    ReaderQos, &L_Aircraft);
	Sub->create_datareader(T_Fire,        ReaderQos, &L_Fire);
	Sub->create_datareader(T_Detonation,  ReaderQos, &L_Detonation);
	Sub->create_datareader(T_Emission,    ReaderQos, &L_Emission);
	Sub->create_datareader(T_Transmitter, ReaderQos, &L_Transmitter);
	Sub->create_datareader(T_Signal,      ReaderQos, &L_Signal);

	std::cout << "subscribed to 6 topics, waiting for samples...\n\n";

	// Periodically print a running total so the operator can see the
	// subscriber is alive even when there's no traffic. - TripleA
	auto Last = std::chrono::steady_clock::now();
	std::uint64_t LastCount = 0;
	while (!gShouldExit.load())
	{
		std::this_thread::sleep_for(std::chrono::seconds(5));
		const std::uint64_t Now = gReceivedCount.load();
		const std::uint64_t Delta = Now - LastCount;
		LastCount = Now;
		std::cerr << "  [rate] total received: " << Now
		          << " (+" << Delta << " in last 5s)\n";
	}

	std::cout << "\nshutting down. total received: " << gReceivedCount.load() << "\n";
	Participant->delete_contained_entities();
	Factory->delete_participant(Participant);
	return 0;
}
